const res1 = {
  marker: "12345678999",
  next: "https://api.sit.etrade.com/accounts/E5Nd4LJBsEi_UyHm4Vio9g/orders?marker=12345678999",
  Order: [
    {
      orderType: "OPTN",
      totalOrderValue: "330.4644",
      Order: {
        orderTerm: "GOOD_FOR_DAY",
        priceType: "MARKET",
        limitPrice: "0",
        stopPrice: "0",
        marketSession: "REGULAR",
        allOrNone: "false",
        Instrument: {
          Product: {
            symbol: "FB",
            securityType: "OPTN",
            callPut: "CALL",
            expiryYear: "2018",
            expiryMonth: "12",
            expiryDay: "21",
            strikePrice: "140.00",
            productId: {
              symbol: "FB----210409P00297500",
              typeCode: "OPTION",
            },
          },
          symbolDescription: "FB Dec 21 '18 $140 Call",
          orderAction: "BUY_OPEN",
          quantityType: "QUANTITY",
          quantity: "1",
          cancelQuantity: "0.0",
          osiKey: "FB----181221C00140000",
          reserveOrder: "true",
          reserveQuantity: "0.0",
        },
        egQual: "EG_QUAL_NOT_AN_ELIGIBLE_SECURITY",
        estimatedCommission: "5.45",
        estimatedTotalAmount: "330.4644",
        netPrice: "0",
        netBid: "0",
        netAsk: "0",
        gcd: "0",
        ratio: [],
      },
      PreviewIds: {
        previewId: "2785277279",
      },
      previewTime: "1544038038415",
      dstFlag: "false",
      accountId: "314497960",
      optionLevelCd: "4",
      marginLevelCd: "MARGIN_TRADING_ALLOWED",
      Disclosure: {
        aoDisclosureFlag: "true",
        conditionalDisclosureFlag: "true",
      },
      marginable: {
        currentBp: "400000.00",
        currentNetBp: "400000.00",
        currentOor: "0.00",
        currentOrderImpact: "296.95",
        netBp: "399703.05",
      },
      nonMarginable: {
        currentBp: "200000.00",
        currentNetBp: "200000.00",
        currentOor: "0.00",
        currentOrderImpact: "296.95",
        netBp: "199703.05",
      },
    },
    {
      orderId: 479,
      details:
        "https://api.etrade.com/accounts/E5Nd4LJBsEi_UyHm4Vio9g/orders/479",
      orderType: "OPTN",
      OrderDetail: [
        {
          placedTime: 123453456,
          orderValue: 123,
          status: "OPEN",
          orderTerm: "GOOD_FOR_DAY",
          priceType: "LIMIT",
          limitPrice: 1.5,
          stopPrice: 0,
          marketSession: "REGULAR",
          allOrNone: false,
          netPrice: 0,
          netBid: 0,
          netAsk: 0,
          gcd: 0,
          ratio: "",
          Instrument: [
            {
              symbolDescription: "RESEARCH IN MOTION LTD COM",
              orderAction: "BUY_OPEN",
              quantityType: "QUANTITY",
              orderedQuantity: 5,
              filledQuantity: 5,
              averageExecutionPrice: 0,
              estimatedCommission: 9.99,
              estimatedFees: 0,
              Product: {
                symbol: "RIMM",
                securityType: "OPTN",
                callPut: "CALL",
                expiryYear: 2012,
                expiryMonth: 3,
                expiryDay: 9,
                strikePrice: 12,
                productId: {
                  symbol: "RIMM",
                },
              },
            },
          ],
        },
      ],
    },
    {
      orderId: 477,
      details:
        "https://api.etrade.com/accounts/E5Nd4LJBsEi_UyHm4Vio9g/orders/477",
      orderType: "ONE_CANCELS_ALL",
      totalOrderValue: 209.99,
      totalCommission: 10.74,
      OrderDetail: [
        {
          orderNumber: 1,
          placedTime: 1331699203122,
          orderValue: 123,
          status: "OPEN",
          orderTerm: "GOOD_FOR_DAY",
          priceType: "LIMIT",
          limitPrice: 2,
          stopPrice: 0,
          marketSession: "REGULAR",
          bracketedLimitPrice: 2,
          initialStopPrice: 2,
          allOrNone: false,
          netPrice: 0,
          netBid: 0,
          netAsk: 0,
          gcd: 0,
          ratio: "",
          Instrument: [
            {
              symbolDescription: "ETRADE Financials",
              orderAction: "BUY",
              quantityType: "QUANTITY",
              orderedQuantity: 100,
              filledQuantity: 0,
              averageExecutionPrice: 0,
              estimatedCommission: 9.99,
              estimatedFees: 0,
              Product: {
                symbol: "ETFC",
                securityType: "EQ",
                productId: {
                  symbol: "ETFC",
                },
              },
            },
          ],
        },
        {
          orderNumber: 2,
          placedTime: 1331699203,
          orderValue: 231,
          status: "OPEN",
          orderTerm: "GOOD_FOR_DAY",
          priceType: "LIMIT",
          limitPrice: 0.5,
          stopPrice: 0,
          marketSession: "REGULAR",
          initialStopPrice: 0.5,
          allOrNone: false,
          netPrice: 0,
          netBid: 0,
          netAsk: 0,
          gcd: 0,
          ratio: "",
          Instrument: [
            {
              symbolDescription: "MON Mar 9 '12 $85 Call",
              orderAction: "BUY_OPEN",
              quantityType: "QUANTITY",
              orderedQuantity: 1,
              filledQuantity: 0,
              averageExecutionPrice: 0,
              estimatedCommission: 9.99,
              estimatedFees: 0,
              Product: {
                symbol: "MON",
                securityType: "OPTN",
                callPut: "CALL",
                expiryYear: 2012,
                expiryMonth: 4,
                expiryDay: 21,
                strikePrice: 85,
                productId: {
                  symbol: "MON",
                },
              },
            },
          ],
        },
      ],
    },
    {
      orderId: 475,
      details:
        "https://api.etrade.com/accounts/E5Nd4LJBsEi_UyHm4Vio9g/orders/475",
      orderType: "SPREADS",
      OrderDetail: [
        {
          placedTime: 1331742953,
          executedTime: 1331742955432,
          orderValue: 4445.99,
          status: "EXECUTED",
          orderTerm: "GOOD_FOR_DAY",
          priceType: "NET_DEBIT",
          limitPrice: 1.5,
          stopPrice: 0,
          marketSession: "REGULAR",
          allOrNone: false,
          netPrice: 0,
          netBid: 0,
          netAsk: 0,
          gcd: 0,
          ratio: "",
          Instrument: [
            {
              symbolDescription: "REE Jul 21 '12 $7 Call",
              orderAction: "BUY_OPEN",
              quantityType: "QUANTITY",
              orderedQuantity: 2,
              filledQuantity: 2,
              averageExecutionPrice: 1.5,
              estimatedCommission: 7.24,
              estimatedFees: 0,
              Product: {
                symbol: "REE",
                securityType: "OPTN",
                callPut: "CALL",
                expiryYear: 2012,
                expiryMonth: 7,
                expiryDay: 21,
                strikePrice: 7,
                productId: {
                  symbol: "REE",
                },
              },
            },
            {
              symbolDescription: "REE Jan 19 '13 $12.50 Put",
              orderAction: "BUY_OPEN",
              quantityType: "QUANTITY",
              orderedQuantity: 2,
              filledQuantity: 2,
              averageExecutionPrice: 1.5,
              estimatedCommission: 7.24,
              estimatedFees: 0,
              Product: {
                symbol: "REE",
                securityType: "OPTN",
                callPut: "PUT",
                expiryYear: 2013,
                expiryMonth: 1,
                expiryDay: 19,
                strikePrice: 12.5,
                productId: {
                  symbol: "REE",
                },
              },
            },
          ],
        },
      ],
    },
  ],
};
const res2 = {
  marker: "12345678999",
  next: "https://api.sit.etrade.com/accounts/E5Nd4LJBsEi_UyHm4Vio9g/orders?marker=12345678999",
  Order: [
    {
      orderType: "SPREADS",
      dstFlag: false,
      optionLevelCd: 4,
      marginLevelCd: "MARGIN_TRADING_ALLOWED",
      placedTime: 1549316465349,
      accountId: "838796270",
      Order: [
        {
          orderTerm: "GOOD_FOR_DAY",
          priceType: "NET_DEBIT",
          limitPrice: 5,
          stopPrice: 0,
          marketSession: "REGULAR",
          allOrNone: false,
          messages: {
            Message: [
              {
                description:
                  "200|The market was closed when we received your order. It has been entered into our system and will be reviewed prior to market open on the next regular trading day. After market open, please check to make sure your order was accepted.",
                code: 1027,
                type: "WARNING",
              },
            ],
          },
          egQual: "EG_QUAL_NOT_AN_ELIGIBLE_SECURITY",
          estimatedCommission: 8.44,
          estimatedTotalAmount: 508.4762,
          netPrice: 0,
          netBid: 0,
          netAsk: 0,
          gcd: 0,
          ratio: "",
          Instrument: [
            {
              symbolDescription: "IBM Feb 15 '19 $130 Call",
              orderAction: "BUY_OPEN",
              quantityType: "QUANTITY",
              quantity: 1,
              cancelQuantity: 0,
              osiKey: "IBM---190215C00130000",
              reserveOrder: true,
              reserveQuantity: 0,
              Product: {
                symbol: "IBM",
                securityType: "OPTN",
                callPut: "CALL",
                expiryYear: 2019,
                expiryMonth: 2,
                expiryDay: 15,
                strikePrice: 130,
              },
            },
            {
              symbolDescription: "IBM Feb 15 '19 $131 Call",
              orderAction: "SELL_OPEN",
              quantityType: "QUANTITY",
              quantity: 1,
              cancelQuantity: 0,
              osiKey: "IBM---190215C00131000",
              reserveOrder: true,
              reserveQuantity: 0,
              Product: {
                symbol: "IBM",
                securityType: "OPTN",
                callPut: "CALL",
                expiryYear: 2019,
                expiryMonth: 2,
                expiryDay: 15,
                strikePrice: 131,
              },
            },
          ],
        },
      ],
      OrderIds: [
        {
          orderId: 484,
        },
      ],
    },
    {
      orderType: "EQ",
      dstFlag: false,
      optionLevelCd: 4,
      marginLevelCd: "MARGIN_TRADING_ALLOWED",
      placedTime: 1549318099447,
      accountId: "838796270",
      Order: [
        {
          orderTerm: "GOOD_FOR_DAY",
          priceType: "LIMIT",
          limitPrice: 169,
          stopPrice: 0,
          marketSession: "REGULAR",
          allOrNone: false,
          messages: {
            Message: [
              {
                description:
                  "200|The market was closed when we received your order. It has been entered into our system and will be reviewed prior to market open on the next regular trading day. After market open, please check to make sure your order was accepted.",
                code: 1027,
                type: "WARNING",
              },
            ],
          },
          egQual: "EG_QUAL_NOT_A_MARKET_ORDER",
          estimatedCommission: 6.95,
          estimatedTotalAmount: 175.95,
          netPrice: 0,
          netBid: 0,
          netAsk: 0,
          gcd: 0,
          ratio: "",
          Instrument: [
            {
              symbolDescription: "FACEBOOK INC CL A",
              orderAction: "BUY",
              quantityType: "QUANTITY",
              quantity: 1,
              cancelQuantity: 0,
              reserveOrder: true,
              reserveQuantity: 0,
              Product: {
                symbol: "FB",
                securityType: "EQ",
              },
            },
          ],
        },
      ],
    },
    {
      orderId: 479,
      details:
        "https://api.etrade.com/accounts/E5Nd4LJBsEi_UyHm4Vio9g/orders/479",
      orderType: "OPTN",
      OrderDetail: [
        {
          placedTime: 123453456,
          orderValue: 123,
          status: "OPEN",
          orderTerm: "GOOD_FOR_DAY",
          priceType: "LIMIT",
          limitPrice: 1.5,
          stopPrice: 0,
          marketSession: "REGULAR",
          allOrNone: false,
          netPrice: 0,
          netBid: 0,
          netAsk: 0,
          gcd: 0,
          ratio: "",
          Instrument: [
            {
              symbolDescription: "RESEARCH IN MOTION LTD COM",
              orderAction: "BUY_OPEN",
              quantityType: "QUANTITY",
              orderedQuantity: 5,
              filledQuantity: 5,
              averageExecutionPrice: 0,
              estimatedCommission: 9.99,
              estimatedFees: 0,
              Product: {
                symbol: "RIMM",
                securityType: "OPTN",
                callPut: "CALL",
                expiryYear: 2012,
                expiryMonth: 3,
                expiryDay: 9,
                strikePrice: 12,
                productId: {
                  symbol: "RIMM",
                },
              },
            },
          ],
        },
      ],
    },
    {
      orderId: 477,
      details:
        "https://api.etrade.com/accounts/E5Nd4LJBsEi_UyHm4Vio9g/orders/477",
      orderType: "ONE_CANCELS_ALL",
      totalOrderValue: 209.99,
      totalCommission: 10.74,
      OrderDetail: [
        {
          orderNumber: 1,
          placedTime: 1331699203122,
          orderValue: 123,
          status: "OPEN",
          orderTerm: "GOOD_FOR_DAY",
          priceType: "LIMIT",
          limitPrice: 2,
          stopPrice: 0,
          marketSession: "REGULAR",
          bracketedLimitPrice: 2,
          initialStopPrice: 2,
          allOrNone: false,
          netPrice: 0,
          netBid: 0,
          netAsk: 0,
          gcd: 0,
          ratio: "",
          Instrument: [
            {
              symbolDescription: "ETRADE Financials",
              orderAction: "BUY",
              quantityType: "QUANTITY",
              orderedQuantity: 100,
              filledQuantity: 0,
              averageExecutionPrice: 0,
              estimatedCommission: 9.99,
              estimatedFees: 0,
              Product: {
                symbol: "ETFC",
                securityType: "EQ",
                productId: {
                  symbol: "ETFC",
                },
              },
            },
          ],
        },
        {
          orderNumber: 2,
          placedTime: 1331699203,
          orderValue: 231,
          status: "OPEN",
          orderTerm: "GOOD_FOR_DAY",
          priceType: "LIMIT",
          limitPrice: 0.5,
          stopPrice: 0,
          marketSession: "REGULAR",
          initialStopPrice: 0.5,
          allOrNone: false,
          netPrice: 0,
          netBid: 0,
          netAsk: 0,
          gcd: 0,
          ratio: "",
          Instrument: [
            {
              symbolDescription: "MON Mar 9 '12 $85 Call",
              orderAction: "BUY_OPEN",
              quantityType: "QUANTITY",
              orderedQuantity: 1,
              filledQuantity: 0,
              averageExecutionPrice: 0,
              estimatedCommission: 9.99,
              estimatedFees: 0,
              Product: {
                symbol: "MON",
                securityType: "OPTN",
                callPut: "CALL",
                expiryYear: 2012,
                expiryMonth: 4,
                expiryDay: 21,
                strikePrice: 85,
                productId: {
                  symbol: "MON",
                },
              },
            },
          ],
        },
      ],
    },
    {
      orderId: 475,
      details:
        "https://api.etrade.com/accounts/E5Nd4LJBsEi_UyHm4Vio9g/orders/475",
      orderType: "SPREADS",
      OrderDetail: [
        {
          placedTime: 1331742953,
          executedTime: 1331742955432,
          orderValue: 4445.99,
          status: "EXECUTED",
          orderTerm: "GOOD_FOR_DAY",
          priceType: "NET_DEBIT",
          limitPrice: 1.5,
          stopPrice: 0,
          marketSession: "REGULAR",
          allOrNone: false,
          netPrice: 0,
          netBid: 0,
          netAsk: 0,
          gcd: 0,
          ratio: "",
          Instrument: [
            {
              symbolDescription: "REE Jul 21 '12 $7 Call",
              orderAction: "BUY_OPEN",
              quantityType: "QUANTITY",
              orderedQuantity: 2,
              filledQuantity: 2,
              averageExecutionPrice: 1.5,
              estimatedCommission: 7.24,
              estimatedFees: 0,
              Product: {
                symbol: "REE",
                securityType: "OPTN",
                callPut: "CALL",
                expiryYear: 2012,
                expiryMonth: 7,
                expiryDay: 21,
                strikePrice: 7,
                productId: {
                  symbol: "REE",
                },
              },
            },
            {
              symbolDescription: "REE Jan 19 '13 $12.50 Put",
              orderAction: "BUY_OPEN",
              quantityType: "QUANTITY",
              orderedQuantity: 2,
              filledQuantity: 2,
              averageExecutionPrice: 1.5,
              estimatedCommission: 7.24,
              estimatedFees: 0,
              Product: {
                symbol: "REE",
                securityType: "OPTN",
                callPut: "PUT",
                expiryYear: 2013,
                expiryMonth: 1,
                expiryDay: 19,
                strikePrice: 12.5,
                productId: {
                  symbol: "REE",
                },
              },
            },
          ],
        },
      ],
    },
  ],
};
export { res1, res2 };
